"""
nova.engine.synthesize — Synthesize Engine: takes → structured KB pages.

Called by BrainWatcher when brain.db accumulates +15 new takes.
Medium weight, 5-min cooldown.

What it does:
  1. Groups recent takes by holder (agent)
  2. Writes/updates a KB synthesis page per holder
  3. Records a SYNTHESIS_DONE event in brain.db
"""

from __future__ import annotations

import argparse
import os
import sqlite3
import uuid
from collections import defaultdict
from datetime import date, datetime, timezone
from pathlib import Path


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def run(nova_home: Path) -> int:
    """Synthesise takes into KB pages. Returns count of pages written."""
    brain_db = nova_home / "brain.db"
    kb_dir = nova_home / "kb" / "synthesis"

    if not brain_db.exists():
        print("[synthesize] brain.db not found — skip")
        return 0

    db = sqlite3.connect(str(brain_db), timeout=10)
    db.row_factory = sqlite3.Row

    # Recent takes (last 50, grouped by holder)
    rows = db.execute(
        "SELECT id, holder, claim, weight, created_at FROM takes "
        "ORDER BY created_at DESC LIMIT 50"
    ).fetchall()

    if not rows:
        print("[synthesize] no takes — skip")
        db.close()
        return 0

    by_holder: dict[str, list] = defaultdict(list)
    for r in rows:
        by_holder[r["holder"] or "nova"].append(r)

    kb_dir.mkdir(parents=True, exist_ok=True)
    today = date.today().isoformat()
    written = 0

    for holder, takes in by_holder.items():
        slug = holder.replace("/", "-").replace(" ", "-")
        out = kb_dir / f"{slug}-{today}.md"

        lines = [
            f"---\ntitle: {holder} synthesis {today}\ntype: synthesis\nagent: {holder}\n"
            f"created: {today}\n---\n\n"
            f"# {holder} — Synthesis {today}\n\n"
            f"> Auto-generated by nova.engine.synthesize from {len(takes)} takes.\n\n"
            "## Knowledge Takes\n"
        ]
        for t in sorted(takes, key=lambda x: -x["weight"]):
            lines.append(f"- **[w={t['weight']:.2f}]** {t['claim'][:300]}")

        out.write_text("\n".join(lines) + "\n", encoding="utf-8")
        written += 1

    # Emit SYNTHESIS_DONE event
    try:
        eid = uuid.uuid4().hex[:16]
        db.execute(
            "INSERT INTO nova_events (id,event_type,severity,title,detail,source,created_at,is_read) "
            "VALUES (?,?,?,?,?,?,?,?)",
            (eid, "SYNTHESIS_DONE", "INFO",
             f"Synthesis complete — {written} pages, {len(rows)} takes",
             f"holders: {list(by_holder.keys())}",
             "nova.engine.synthesize", _now(), 0),
        )
        db.commit()
    except Exception:
        pass  # events table may not exist in minimal setups

    db.close()
    print(f"[synthesize] wrote {written} pages from {len(rows)} takes")
    return written


def main() -> None:
    parser = argparse.ArgumentParser(description="NOVA Synthesize Engine")
    parser.add_argument("--nova-home", default=os.environ.get("NOVA_HOME", "~/.nova"))
    args = parser.parse_args()
    nova_home = Path(args.nova_home).expanduser().resolve()
    nova_home.mkdir(parents=True, exist_ok=True)
    run(nova_home)


if __name__ == "__main__":
    main()
